name: vee_app
version: 1.0.0+1
publish_to: 'none'
description: Application for managing charitable activities

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  core:
    path: core
  core_ui:
    path: core_ui
  navigation:
    path: navigation


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - localization/

  fonts:
    - family: Poppins
      fonts:
        - asset: core_ui/resources/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 100
        - asset: core_ui/resources/fonts/poppins/Poppins-Light.ttf
          weight: 200
        - asset: core_ui/resources/fonts/poppins/Poppins-Regular.ttf
          weight: 300
        - asset: core_ui/resources/fonts/poppins/Poppins-Medium.ttf
          weight: 400
        - asset: core_ui/resources/fonts/poppins/Poppins-SemiBold.ttf
          weight: 500
        - asset: core_ui/resources/fonts/poppins/Poppins-Bold.ttf
          weight: 600
        - asset: core_ui/resources/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 700