name: core
version: 0.0.1
publish_to: none
description: Core of the application

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  intl: ^0.17.0
  get_it: ^7.2.0
  rxdart: ^0.27.5
  equatable: ^2.0.3
  flutter_bloc: ^7.3.3
  connectivity: ^3.0.3
  flutter_i18n: ^0.32.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
